### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by johnlees** [jschnab/pyms-plot#2]
This is required for JOSS (and the version should match that in the review 0.8.1) (see https://github.com/openjournals/joss-reviews/issues/1125)

**Comment by jschnab** [comment]
@johnlees  - Hi, sorry but I don't understand what I should do, exactly. Can you explain how I can tag a release?

Edit: I think I figured out, please let me know if it's OK. After having a look at other projects published in JOSS, I will add another release once I have a PyMS version accepted for publication.

**Comment by johnlees** [comment]
Looks good to me now!
