### ISSUE TITLE
Check references in paper

### ISSUE THREAD

**Issue by johnlees** [jschnab/pyms-plot#3]
openjournals/joss-reviews#1125

**References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?**

These look ok to me, but could you confirm whether DOIs are available for the references, and add them if they are?

You may wish to add one reference to either an example of where pyms has been used (e.g. to generate plots for a paper) or one to an example dataset of quantitative analysis of mycorrhizal fungi colonization of plant roots.
I would suggest adding both the references from the `README.md` to the paper too

**Comment by jschnab** [comment]
For the python libraries references, I followed [these guidelines](https://www.scipy.org/citing.html).

So far, PyMS was not used in a publication that was submitted to a journal, I will update the GitHub repository when this happens.

I added the two articles referenced in the `README.md` to the paper, the one from 2018 contains an example of a quantitative analysis which can be performed using PyMS.
