### ISSUE TITLE
Add expected output to docs

### ISSUE THREAD

**Issue by johnlees** [jschnab/pyms-plot#5]
https://github.com/openjournals/joss-reviews/issues/1125
**Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?**

For the docs (either in the `README.md` or on readthedocs) I think you should add at least one image showing the expected output for the test case example

**Comment by johnlees** [comment]
You should also add an example of the statistical test output, and explain what the columns are

**Comment by jschnab** [comment]
I added images showing the expected outputs (plot and statistical tests) in both README.md and readthedocs.
