### ISSUE TITLE
Add further method documentation

### ISSUE THREAD

**Issue by johnlees** [jschnab/pyms-plot#6]
https://github.com/openjournals/joss-reviews/issues/1125

**Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?**

There is a description of the statistical tests in the paper, but I believe it would be helpful to add these descriptions to either the `README.md` or readthedocs

**Comment by johnlees** [comment]
Also please explain briefly in the docs which statistical tests should be used in which circumstances

**Comment by jschnab** [comment]
I added a description and quick guide of the statistical tests to the README.md and readthedocs.
